"use client";
import CharacterDetails, { characterImage } from "./CharacterDetails";
import { useState } from "react";
import { Icon } from "./StudioBrand";
import { characterRoles, type WorldEntry } from "./project-types";
import "./characters.css";
const tabs = ["All Characters", ...characterRoles, "Drafts"];
export default function CharactersView({characters,query,onQuery,onCreate,onEdit,notice}:{characters:WorldEntry[];query:string;onQuery:(value:string)=>void;onCreate:()=>void;onEdit:(entry:WorldEntry)=>void;notice:string}) {
  const [tab,setTab]=useState("All Characters");
  const [filters,setFilters]=useState(false);
  const [stage,setStage]=useState("All");
  const [sort,setSort]=useState("importance");
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const state=(c:WorldEntry)=>c.characterState || (c.status==="Completed"?"Ready":"Draft");
  const visible=characters.filter(c=>(tab==="All Characters" || (tab==="Drafts"?state(c)==="Draft":(c.characterRole||"Supporting")===tab)) && (stage==="All" || state(c)===stage) && `${c.title} ${c.description} ${c.characterTraits||""} ${c.characterRole||"Supporting"} ${Object.values(c.characterProfile||{}).join(" ")}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==="name"?a.title.localeCompare(b.title):sort==="importance"?characterRoles.indexOf(a.characterRole||"Supporting")-characterRoles.indexOf(b.characterRole||"Supporting"):(Date.parse(b.updatedAt)||0)-(Date.parse(a.updatedAt)||0));
  const selected=visible.find(c=>c.id===selectedId)||visible[0];
  function selectCharacter(id:string){setSelectedId(id);if(window.innerWidth<=1050)requestAnimationFrame(()=>document.querySelector(".character-detail")?.scrollIntoView({behavior:"auto",block:"start"}));}
  function clear(){setTab("All Characters");setStage("All");onQuery("");}
  return <div className={`characters-page ${characters.length?"characters-populated":""}`}>
    <section className="characters-hero"><h1>Characters</h1><h2>Bring your world to life.</h2><p>Create and manage your characters, their stories, relationships, and development<br className="characters-wide-break"/> across episodes.</p><blockquote>“Memorable stories<br/>start with unforgettable<br/>characters.”</blockquote></section>
    <div className="characters-toolbar"><div className="character-tabs" role="tablist" aria-label="Character categories">{tabs.map(name=><button role="tab" key={name} aria-selected={tab===name} tabIndex={tab===name?0:-1} onClick={()=>setTab(name)} onKeyDown={e=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();const index=(tabs.indexOf(name)+(e.key==="ArrowRight"?1:tabs.length-1))%tabs.length;setTab(tabs[index]);(e.currentTarget.parentElement?.children[index] as HTMLElement)?.focus();}}}>{name}</button>)}</div><div className="character-tools">{characters.length ? <><label className="character-select">Sort:<select aria-label="Sort characters" value={sort} onChange={e=>setSort(e.target.value)}><option value="importance">Importance</option><option value="updated">Last Updated</option><option value="name">Name A–Z</option></select></label><label className="character-select">Filter:<select aria-label="Filter characters" value={stage} onChange={e=>setStage(e.target.value)}><option>All</option><option>Draft</option><option>Ready</option></select></label></> : <><label className="character-search"><Icon name="Search" size={17}/><input value={query} onChange={e=>onQuery(e.target.value)} placeholder="Search characters…" aria-label="Search characters"/></label><button className="project-secondary character-filter" aria-expanded={filters} aria-controls="character-filter-options" onClick={()=>setFilters(!filters)}><Icon name="Timeline" size={16}/> Filter{stage!=="All"&&<span className="filter-dot"/>}</button></>}<button className="project-primary" onClick={onCreate}><span aria-hidden="true">＋</span> New Character</button></div></div>
    {filters&&!characters.length&&<div className="character-filter-options" id="character-filter-options"><label>Status<select value={stage} onChange={e=>setStage(e.target.value)}><option>All</option><option>Draft</option><option>Ready</option></select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="importance">Importance</option><option value="updated">Last updated</option><option value="name">Name A–Z</option></select></label><button onClick={clear}>Reset filters</button></div>}
    {!characters.length?<section className="characters-empty"><img className="empty-cast-art" src="/images/characters/empty-cast.png" alt=""/><div className="characters-empty-copy"><h2>No characters yet.</h2><p>Every great story starts with a cast. Create your first character and bring<br className="characters-wide-break"/> your world to life.</p><button className="project-primary" onClick={onCreate}><span aria-hidden="true">＋</span> Create Your First Character</button></div><div className="character-benefits">{[["Characters","Build rich profiles","Name, background, role, personality, abilities, and more."],["Relationships","Connect their stories","Develop the connections that shape your world and episodes."],["Lore","Bring them to life","Keep your cast at the heart of your episodes, scenes, and story."]].map(([icon,title,description])=><article key={title}><span className="character-benefit-icon"><Icon name={icon} size={26}/></span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>:visible.length?<section className="character-library character-library-split" aria-label="Characters"><div className="character-grid">{visible.map(c=><article className={`character-card ${selected?.id===c.id?"is-selected":""}`} key={c.id}><button className="character-card-select" onClick={()=>selectCharacter(c.id)} aria-label={`View ${c.title}`} aria-pressed={selected?.id===c.id}><div className="character-portrait"><img src={characterImage(c)} alt=""/></div><div className="character-card-copy"><h2>{c.title}</h2><span>{c.characterProfile?.storyRole||c.characterRole||"Supporting"}</span><p>{c.description || "A new story waiting to be told."}</p><div className="character-tag-list">{[c.characterProfile?.race,c.characterRole||"Supporting",c.characterProfile?.specialty].filter(Boolean).map((tag,i)=><span key={i}>{tag}</span>)}</div></div></button><button className="character-card-menu" aria-label={`Manage ${c.title}`} onClick={()=>onEdit(c)}>•••</button></article>)}</div>{selected&&<CharacterDetails key={selected.id} character={selected} onEdit={onEdit}/>}</section>:<section className="characters-no-results"><Icon name="Search" size={32}/><h2>No matching characters.</h2><p>Try another name, role, or filter.</p><button className="project-secondary" onClick={clear}>Show All Characters</button></section>}
    <p role="status" className="pw-save-notice">{notice}</p>
  </div>;
}
