"use client";
import { useEffect, useRef, useState } from "react";
import { Icon } from "./StudioBrand";
import { projectArt, type WorldEntry } from "./project-types";
import { episodeStage, episodeStages, type EpisodeStage, type EpisodeTemplate } from "./episode-model";
export default function EpisodeEditor({entry,template,defaultCover,onClose,onSave,notice}:{entry?:WorldEntry;template?:EpisodeTemplate|null;defaultCover?:string;onClose:()=>void;onSave:(entry:WorldEntry)=>boolean;notice:string}){
  const dialog=useRef<HTMLDialogElement>(null);
  const [name,setName]=useState(entry?.title||"");const [description,setDescription]=useState(entry?.description||"");const [stage,setStage]=useState<EpisodeStage>(entry?episodeStage(entry):"Planned");
  const [date,setDate]=useState(entry?.dueDate||"");const [tags,setTags]=useState((entry?.episodeTags||[]).join(", "));const [outline,setOutline]=useState(entry?.outline||template?.outline||"");const [script,setScript]=useState(entry?.script||"");const [cover,setCover]=useState(entry?.cover||template?.cover||defaultCover||"fantasy");const [progress,setProgress]=useState(entry?.productionProgress===undefined?"":String(entry.productionProgress));
  useEffect(()=>{dialog.current?.showModal();},[]);
  function save(){const now=new Date().toISOString();onSave({...entry,id:entry?.id||crypto.randomUUID(),kind:"Episodes",title:name.trim(),description:description.trim(),status:stage==="Completed"?"Completed":stage==="In Production"?"In progress":"Not started",episodeStage:stage,dueDate:date||undefined,episodeTags:tags.split(",").map(t=>t.trim()).filter(Boolean).slice(0,8),outline,script,cover,createdAt:entry?.createdAt||entry?.updatedAt||now,updatedAt:now,productionProgress:stage==="Completed"?100:progress===""?undefined:Math.max(0,Math.min(99,Number(progress))),episodeTemplate:entry?.episodeTemplate||template?.name});}
  return <dialog ref={dialog} className="studio-dialog project-editor episode-editor" onCancel={onClose}><button className="project-dialog-close" aria-label="Close episode editor" onClick={onClose}>×</button><form onSubmit={e=>{e.preventDefault();if(name.trim())save();}}><p className="studio-eyebrow">YOUR NEXT CHAPTER</p><h2>{entry?"Edit Episode":"New Episode"}</h2>{template&&<p className="episode-template-note">{template.name} · Suggested length: {template.length}. Use the outline as a starting point.</p>}<label>Name<input aria-label="Episode name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Synopsis<textarea aria-label="Episode synopsis" maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="episode-editor-grid"><label>Status<select aria-label="Episode status" value={stage} onChange={e=>setStage(e.target.value as EpisodeStage)}>{episodeStages.map(s=><option key={s}>{s}</option>)}</select></label><label>Planned release date<input aria-label="Planned release date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{stage==="In Production"&&<label>Production progress (%)<input aria-label="Production progress" type="number" min="0" max="99" placeholder="Optional" value={progress} onChange={e=>setProgress(e.target.value)}/></label>}<label>Tags, separated by commas<input aria-label="Episode tags" maxLength={300} value={tags} onChange={e=>setTags(e.target.value)} placeholder="Adventure, Mystery, Character Intro"/></label><label>Outline<textarea aria-label="Episode outline" maxLength={50000} value={outline} onChange={e=>setOutline(e.target.value)} placeholder="Shape the beginning, turning points, and ending…"/></label><label>Script<textarea aria-label="Episode script" maxLength={100000} value={script} onChange={e=>setScript(e.target.value)} placeholder="Write your scenes and dialogue…"/></label><fieldset><legend>Cover artwork</legend><div className="project-cover-choices">{projectArt.map(c=><button type="button" key={c} aria-label={`${c} cover`} aria-pressed={cover===c} className={cover===c?"selected":""} onClick={()=>setCover(c)}><img src={`/images/generated/${c}.webp`} alt=""/></button>)}</div></fieldset><button className="project-primary" type="submit">Save Episode <Icon name="Arrow" size={17}/></button><p role="status">{notice}</p></form></dialog>;
}
