"use client";
import { useState } from "react";
import { Icon } from "./StudioBrand";
import { episodeStage, episodeStages, episodeTemplates, type EpisodeTemplate } from "./episode-model";
import { projectArt, type Draft, type WorldEntry } from "./project-types";
import "./episodes.css";
const art=(cover?:string)=>`/images/generated/${projectArt.includes(cover||"")?cover:"fantasy"}.webp`;
const date=(value?:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"Not scheduled";
const tabs=["All Episodes","In Development","In Production","Completed","Archived"];
export default function EpisodesView({project,episodes,query,onQuery,onCreate,onEdit,onSave,onNavigate,notice}:{project:Draft;episodes:WorldEntry[];query:string;onQuery:(q:string)=>void;onCreate:(template?:EpisodeTemplate)=>void;onEdit:(entry:WorldEntry)=>void;onSave:(patch:Partial<Draft>,action:string)=>boolean;onNavigate:(name:string)=>void;notice:string}){
  const [tab,setTab]=useState("All Episodes");const [filter,setFilter]=useState("All Status");const [sort,setSort]=useState("Newest");const [menu,setMenu]=useState<string|null>(null);const [allTemplates,setAllTemplates]=useState(false);
  const active=episodes.filter(e=>!e.archived);
  const filtered=episodes.filter(e=>(tab==="Archived"?e.archived:!e.archived)&&(tab==="All Episodes"||tab==="Archived"||tab==="In Development"?["All Episodes","Archived"].includes(tab)||["Planned","In Development"].includes(episodeStage(e)):episodeStage(e)===tab)&&(filter==="All Status"||episodeStage(e)===filter)&&`${e.title} ${e.description} ${e.script||""} ${e.outline||""} ${(e.episodeTags||[]).join(" ")}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="Episode Order"?episodes.indexOf(a)-episodes.indexOf(b):sort==="Target Date"?(a.dueDate||"9999").localeCompare(b.dueDate||"9999"):sort==="Title"?a.title.localeCompare(b.title):(b.createdAt||b.updatedAt).localeCompare(a.createdAt||a.updatedAt));
  function archive(entry:WorldEntry){const archived=!entry.archived;if(onSave({workspace:{...project.workspace,entries:(project.workspace?.entries||[]).map(e=>e.id===entry.id?{...e,archived}:e)}},`${archived?"Archived":"Restored"} episode: ${entry.title}`))setMenu(null);}
  function choose(next:string){setTab(next);setFilter("All Status");setMenu(null);}
  return <><section className="episodes-hero"><h1>Episodes</h1><h2>Turn your story into reality.</h2><p>Plan, write, visualize, and produce each episode. Keep every chapter connected to {project.title}’s Story Bible.</p><blockquote>“From ideas<br/>to unforgettable<br/>episodes.”</blockquote></section>
    <div className="episodes-toolbar"><nav aria-label="Episode categories">{tabs.map(t=><button key={t} aria-current={tab===t?"page":undefined} onClick={()=>choose(t)}>{t}</button>)}</nav><div className="episode-tools"><label className="episode-search"><Icon name="Search" size={18}/><input aria-label="Search episodes" placeholder="Search episodes…" value={query} onChange={e=>onQuery(e.target.value)}/></label><select aria-label="Filter episode status" value={filter} onChange={e=>setFilter(e.target.value)}>{["All Status",...episodeStages].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Sort episodes" value={sort} onChange={e=>setSort(e.target.value)}>{["Newest","Episode Order","Target Date","Title"].map(s=><option key={s}>{s}</option>)}</select><button className="project-primary" onClick={()=>onCreate()}>＋ New Episode</button></div></div>
    <div className="episodes-layout"><div className="episodes-main"><div className="episode-stats">{[["Check","Completed",active.filter(e=>episodeStage(e)==="Completed").length],["Production","In Production",active.filter(e=>episodeStage(e)==="In Production").length],["Timeline","Planned",active.filter(e=>episodeStage(e)==="Planned").length],["Lore","Total Episodes",active.length]].map(([icon,label,count],i)=><button key={String(label)} onClick={()=>{choose(i===2?"In Development":i===3?"All Episodes":String(label));if(i===2)setFilter("Planned");}}><span className={`episode-stat-icon stat-${i}`}><svg className={`episode-stat-symbol symbol-${i}`} width="27" height="27" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{i===1?<circle cx="12" cy="12" r="9" strokeDasharray="49 8"/>:i===2?<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>:null}</svg>{i!==1&&i!==2&&<Icon name={String(icon)} size={27}/>}</span><span><strong>{count}</strong><small>{label}</small></span></button>)}</div>
    <div className="episode-list">{filtered.length?filtered.map(e=>{const stage=episodeStage(e);return <article className="episode-row" key={e.id}><button className="episode-cover" aria-label={`Open episode: ${e.title}`} onClick={()=>onEdit(e)}><img src={art(e.cover)} alt=""/><span>EP {episodes.indexOf(e)+1}</span></button><div className="episode-copy"><button className="episode-title" onClick={()=>onEdit(e)}><span>Episode {episodes.indexOf(e)+1}</span><strong>{e.title}</strong></button><p>{e.description||"Give this chapter a synopsis and start shaping the story."}</p><div className="episode-tags"><span className={`episode-status stage-${episodeStages.indexOf(stage)}`}>{e.archived?"Archived":stage}</span>{(e.episodeTags||[]).slice(0,4).map((tag,i)=><span key={i}>{tag}</span>)}</div></div><div className="episode-actions"><div className="episode-row-heading"><div><span>{stage==="Completed"?"Release Date":"Target Date"}</span><time>{date(e.dueDate)}</time></div><div className="episode-menu"><button aria-label={`Manage episode: ${e.title}`} aria-expanded={menu===e.id} onClick={()=>setMenu(menu===e.id?null:e.id)}>•••</button>{menu===e.id&&<div><button onClick={()=>{setMenu(null);onEdit(e);}}>Edit Episode</button><button onClick={()=>archive(e)}>{e.archived?"Restore Episode":"Archive Episode"}</button><button onClick={()=>setMenu(null)}>Close</button></div>}</div></div>{stage==="In Production"&&e.productionProgress!==undefined&&<div className="episode-progress"><progress aria-label={`Production progress: ${e.title}`} value={e.productionProgress} max={100}/><span>{e.productionProgress}%</span></div>}<button className={`project-secondary ${stage==="In Production"?"continue":""}`} onClick={()=>onEdit(e)}><Icon name={stage==="In Production"?"Arrow":"Edit"} size={16}/>{e.archived?"Review Episode":stage==="Completed"?"Review Episode":stage==="In Production"?"Continue Production":"Start Planning"}</button></div></article>;}):<section className="episodes-empty"><Icon name="Lore" size={38}/><h2>{!episodes.length?"Your first episode starts here.":"No episodes found."}</h2><p>{!episodes.length?"Give your next chapter a name, or start with a template.":"Try a different category, status, or search."}</p>{episodes.length?<button className="project-secondary" onClick={()=>{choose("All Episodes");onQuery("");}}>Clear Filters</button>:<button className="project-primary" onClick={()=>onCreate()}>＋ Create Your First Episode</button>}</section>}</div></div>
    <aside className="episodes-right"><section className="episodes-panel episode-templates"><header><h2>Episode Templates</h2><button onClick={()=>setAllTemplates(v=>!v)}>{allTemplates?"Show Less":"View All"} →</button></header>{episodeTemplates.slice(0,allTemplates?5:3).map(t=><button key={t.name} onClick={()=>onCreate(t)} aria-label={`Use ${t.name} template`}><img src={art(t.cover)} alt=""/><span><strong>{t.name}</strong><span>~{t.length}</span><small>{t.description}</small></span></button>)}</section><section className="episodes-panel episode-quick"><header><h2>Quick Actions</h2></header>{[["Edit","Start an Episode Outline"],["Image","Open Storyboard"],["Lore","Open Story Bible"],["Assets","Visual References"],["Production","Production Tasks"]].map(([icon,label],i)=><button key={label} onClick={()=>i===0?onCreate(episodeTemplates[0]):onNavigate(["","Storyboard","Story Bible","References","Production"][i])}><Icon name={icon} size={20}/><span>{label}</span></button>)}</section><section className="episodes-panel episode-tips"><header><Icon name="Create" size={23}/><h2>Tips</h2></header><div><Icon name="Lore" size={20}/><p>Keep each episode consistent with your Story Bible.<br/><br/>Record new characters, places, and world details there, then review them before confirming canon.</p></div><button onClick={()=>onNavigate("Story Bible")}>Review your world →</button></section></aside></div><p className="episodes-notice" role="status">{notice}</p></>;
}
