"use client";
import { Icon } from "./StudioBrand";
import { projectArt, type Draft, type EntryKind, type WorldEntry } from "./project-types";
import "./project-overview.css";
const art=(cover?:string)=>`/images/generated/${projectArt.includes(cover||"")?cover:"fantasy"}.webp`;
const date=(value?:string)=>value?new Date(value.length===10?`${value}T12:00:00`:value).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"No date set";
export default function ProjectOverview({project,entries,section,query,onNavigate,onCreate,onEdit,onNotes,onProject,onSave,notice}:{project:Draft;entries:WorldEntry[];section:string;query:string;onNavigate:(s:string)=>void;onCreate:(kind:EntryKind)=>void;onEdit:(entry:WorldEntry)=>void;onNotes:()=>void;onProject:()=>void;onSave:(patch:Partial<Draft>,action:string)=>boolean;notice:string}){
  const list=(kind:EntryKind)=>entries.filter(e=>e.kind===kind&&(kind!=="Episodes"||!e.archived));
  const episodes=list("Episodes");const tasks=list("Production");const characters=list("Characters");
  const complete=(rows:WorldEntry[])=>rows.filter(e=>e.status==="Completed").length;
  const world=entries.filter(e=>["Characters","Locations","Factions","Lore","Timeline","Assets"].includes(e.kind)).map(e=>({id:e.id,updatedAt:e.updatedAt}));
  characters.filter(e=>e.characterProfile?.relationships).forEach(e=>world.push({id:`relationships:${e.id}`,updatedAt:e.updatedAt}));
  world.push(...(project.workspace?.bibleEntries||[]));
  const approved=world.filter(e=>project.workspace?.canon?.[e.id]?.status==="Confirmed Canon"&&project.workspace.canon[e.id].revision===e.updatedAt).length;
  const progress=[{name:"Episodes",done:complete(episodes),total:episodes.length},{name:"Story Bible",done:approved,total:world.length},{name:"Assets",done:complete(list("Assets")),total:list("Assets").length},{name:"Production",done:complete(tasks),total:tasks.length}];
  const percent=(done:number,total:number)=>total?Math.round(done/total*100):0;
  const overall=Math.round(progress.reduce((sum,p)=>sum+percent(p.done,p.total),0)/progress.length);
  const activity=project.workspace?.activity||[];
  const upcoming=[...tasks].filter(e=>e.status!=="Completed").sort((a,b)=>(a.dueDate||"9999").localeCompare(b.dueDate||"9999"));
  const matches=entries.filter(e=>`${e.title} ${e.description} ${e.kind}`.toLowerCase().includes(query.toLowerCase()));
  function toggle(entry:WorldEntry){const next=entry.status==="Completed"?"Not started":"Completed";onSave({workspace:{...project.workspace,entries:entries.map(e=>e.id===entry.id?{...e,status:next,updatedAt:new Date().toISOString()}:e)}},`${next==="Completed"?"Completed":"Reopened"} production task: ${entry.title}`);}
  function heading(title:string,action?:()=>void,label="View All"){return <header><h2>{title}</h2>{action&&<button onClick={action}>{label} <Icon name="Arrow" size={15}/></button>}</header>;}
  return <>
    <section className="overview-hero"><h1>{project.title}</h1><p>{project.idea||"Every world starts with an idea. Shape yours here."}</p><div className="project-tags">{(project.tags?.length?project.tags:[project.format,project.style]).filter(Boolean).map((tag,i)=><span key={i}>{tag}</span>)}</div><blockquote>Same world.<br/>New stories.</blockquote><button className="overview-edit" onClick={onProject} aria-label="Edit project details">•••</button></section>
    <nav className="overview-tabs" aria-label="Project overview tabs">{["Overview","Production","Analytics","Team","Settings"].map(s=><button key={s} aria-current={s===section?"page":undefined} onClick={()=>onNavigate(s)}>{s}</button>)}</nav>
    {query?<section className="overview-search overview-panel">{heading("Search results")}<div>{matches.length?matches.map(e=><button key={e.id} onClick={()=>onEdit(e)}><img src={art(e.cover)} alt=""/><span><strong>{e.title}</strong><small>{e.kind}</small></span><Icon name="Arrow" size={16}/></button>):<p>No matching entries in this project.</p>}</div></section>:section==="Analytics"?<section className="overview-analytics overview-panel">{heading("Project Analytics")}<p>Progress from saved work in {project.title}. Overall progress averages these four areas; empty areas count as 0%.</p><div className="overview-analytics-grid">{progress.map(p=><article key={p.name}><h3>{p.name}</h3><strong>{percent(p.done,p.total)}%</strong><p>{p.done} of {p.total} {p.name==="Story Bible"?"entries confirmed as canon":"entries completed"}</p><progress value={p.done} max={p.total||1}/></article>)}</div></section>:section==="Team"?<section className="overview-team overview-panel">{heading("Project Team")}<Icon name="Characters" size={40}/><h3>A place to build together.</h3><p>Team invitations will be available when individual accounts and shared project storage are connected. This project is currently saved in your browser.</p><button className="project-secondary" onClick={()=>onNavigate("Overview")}>Back to Overview</button></section>:<div className="overview-layout"><div className="overview-main">
    <div className="overview-stats">{(["Episodes","Characters","Locations","Factions"] as EntryKind[]).map(kind=><button key={kind} onClick={()=>onNavigate(kind)}><span className="overview-icon"><Icon name={kind==="Episodes"?"Lore":kind} size={27}/></span><span><strong>{list(kind).length}</strong><span>{kind}</span><small>{kind==="Episodes"?`${episodes.filter(e=>e.status==="In progress").length} in production`:kind==="Characters"?`${characters.filter(e=>e.characterRole==="Main Cast").length} main · ${characters.filter(e=>e.characterRole!=="Main Cast").length} other cast`:kind==="Locations"?"Places in your world":`${complete(list(kind))} complete · ${list(kind).length-complete(list(kind))} in development`}</small></span></button>)}</div>
    <section className="overview-panel overview-episodes">{heading("Episodes",()=>onNavigate("Episodes"))}<div className="overview-episode-grid">{episodes.slice(0,4).map((e,i)=><article key={e.id}><button className="overview-episode-open" onClick={()=>onEdit(e)} aria-label={`Open episode: ${e.title}`}><img src={art(e.cover)} alt=""/><span><strong>Episode {i+1}</strong><span>{e.title}</span><small className={`overview-state ${e.status==="Completed"?"complete":e.status==="In progress"?"working":""}`}>{e.status==="In progress"?"In Production":e.status}</small></span></button><footer><time>{date(e.dueDate)}</time><button aria-label={`Edit episode: ${e.title}`} onClick={()=>onEdit(e)}>•••</button></footer></article>)}<button className="overview-new-episode" onClick={()=>onCreate("Episodes")}><span>＋</span><strong>{episodes.length?"New Episode":"Create Your First Episode"}</strong>{!episodes.length&&<small>Start the first chapter of your world.</small>}</button></div></section>
    <section className="overview-panel overview-quick">{heading("Quick Actions")}<div>{[["Create","Create Episode","Start a new chapter"],["Lore","Open Story Bible","Manage your world"],["Image","Manage Visuals","References & assets"],["Edit","Write a Note","Ideas, outlines, scripts"],["Characters","Project Team","Collaboration status"]].map(([icon,label,description],i)=><button key={label} onClick={()=>i===0?onCreate("Episodes"):i===1?onNavigate("Story Bible"):i===2?onNavigate("Visual Style"):i===3?onNotes():onNavigate("Team")}><span className="overview-icon"><Icon name={icon} size={24}/></span><span><strong>{label}</strong><small>{description}</small></span></button>)}</div></section>
    <div className="overview-bottom"><section className="overview-panel overview-timeline">{heading("Production Timeline",()=>onNavigate("Episodes"),"View Full Timeline")}<div>{episodes.length?<ol>{episodes.slice(0,4).map((e,i)=><li key={e.id} className={e.status==="Completed"?"complete":e.status==="In progress"?"working":""}><button onClick={()=>onEdit(e)}><i>{e.status==="Completed"?"✓":""}</i><strong>Ep {i+1}</strong><time>{date(e.dueDate)}</time></button></li>)}</ol>:<div className="overview-empty"><Icon name="Timeline" size={25}/><p>Your episode schedule will appear here.</p><button onClick={()=>onCreate("Episodes")}>Plan an episode →</button></div>}</div></section><section className="overview-panel overview-tasks">{heading("Upcoming Tasks",()=>onNavigate("Production"))}<div>{upcoming.length?upcoming.slice(0,4).map(e=><div className="overview-task" key={e.id}><input type="checkbox" aria-label={`Complete task: ${e.title}`} checked={e.status==="Completed"} onChange={()=>toggle(e)}/><button onClick={()=>onEdit(e)}>{e.title}</button><time>{e.dueDate?date(e.dueDate):"Unscheduled"}</time></div>):<div className="overview-empty"><p>{tasks.length?"You're caught up. All production tasks are complete.":"Add the next steps for your story."}</p><button onClick={()=>onCreate("Production")}>＋ Add a Task</button></div>}</div></section></div>
    </div><aside className="overview-right"><section className="overview-panel overview-progress">{heading("Overall Progress")}<strong>{overall}%</strong><progress value={overall} max={100} aria-label="Overall project progress"/>{progress.map((p,i)=><button key={p.name} onClick={()=>onNavigate(p.name)}><i style={{background:["#ad59ee","#939bc6","#ffb25d","#c7d471"][i]}}/><span>{p.name}</span><b>{p.name==="Episodes"?`${p.done} / ${p.total}`:`${percent(p.done,p.total)}%`}</b></button>)}<small>Completed work and approved canon</small></section>
    <section className="overview-panel overview-activity">{heading("Recent Activity",()=>onNavigate("Activity"))}<div>{activity.length?activity.slice(0,5).map(a=><div key={a.id}><span className="overview-activity-icon"><Icon name="Assets" size={18}/></span><p>{a.text}</p><time>{new Date(a.at).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time></div>):<p className="overview-empty">Your project updates will appear here as you create.</p>}</div></section>
    <section className="overview-panel overview-notes">{heading("Inspiration & Notes")}<div><img src={art(project.cover)} alt="Project inspiration artwork"/>{project.workspace?.notes?<p className="overview-note-text">{project.workspace.notes}</p>:<blockquote>“A greater story<br/>lives in the details.”<span>—</span></blockquote>}</div><button className="project-secondary" onClick={onNotes}>＋ {project.workspace?.notes?"Edit Notes":"Add a Note"}</button></section></aside></div>}
    <p className="overview-notice" role="status">{notice}</p>
  </>;
}
