"use client";
import { useEffect, useRef, useState } from "react";
import { Icon } from "./StudioBrand";
import { bibleCategories, canonStatuses, projectArt, type BibleCategory, type BibleEntry, type CanonStatus, type Draft, type WorldEntry } from "./project-types";
import { bibleEntryKinds } from "./story-bible-model";
import "./story-bible.css";

type BibleItem = BibleEntry & {source?:WorldEntry; status:CanonStatus};
const art=(cover:string)=>`/images/generated/${projectArt.includes(cover)?cover:"fantasy"}.webp`;
const categoryInfo:Record<BibleCategory,[string,string]>={World:["Locations","Rules, magic, cultures, and setting"],Characters:["Characters","Main cast, supporting, and others"],Locations:["Locations","Cities, regions, and landmarks"],Relationships:["Relationships","Allies, rivals, family, and more"],Factions:["Factions","Groups, allegiances, and rival powers"],"Lore & History":["Lore","Ancient events, legends, and truth"],Timeline:["Timeline","The order of your world's events"],"Visual Style":["Image","Art direction, style, and references"],References:["Assets","Inspiration and research notes"],"Canon Rules":["Story Bible","What is always true in your world"]};
const categoryFor:Partial<Record<WorldEntry["kind"],BibleCategory>>={Characters:"Characters",Locations:"Locations",Lore:"Lore & History",Factions:"Factions",Timeline:"Timeline",Assets:"References"};
const date=(value:string)=>new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric"});
export default function StoryBibleView({project,entries,query,onQuery,onSave,onSummary,onEdit,notice,initialCategory,onNavigate}:{initialCategory?:BibleCategory;onNavigate:(section:string)=>void;project:Draft;entries:WorldEntry[];query:string;onQuery:(q:string)=>void;onSave:(patch:Partial<Draft>,action:string)=>boolean;onSummary:()=>void;onEdit:(entry:WorldEntry)=>void;notice:string}) {
  const [tab,setTab]=useState<string>(initialCategory||"Canon");
  const [statusFilter,setStatusFilter]=useState("All statuses");
  const [editing,setEditing]=useState<BibleEntry|null>(null);
  const [open,setOpen]=useState(false);
  const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [category,setCategory]=useState<BibleCategory>("World");const [cover,setCover]=useState("fantasy");const [status,setStatus]=useState<CanonStatus>("Pending Review");
  const [sourceEpisodeId,setSourceEpisodeId]=useState("");
  const [showAll,setShowAll]=useState(false);
  const [feedback,setFeedback]=useState("");
  const dialog=useRef<HTMLDialogElement>(null);const file=useRef<HTMLInputElement>(null);
  const custom=(project.workspace?.bibleEntries||[]).filter(e=>e&&bibleCategories.includes(e.category)&&typeof e.title==="string");
  const canon=project.workspace?.canon||{};
  const sourceItems:BibleEntry[]=[];
  const sources:Record<string,WorldEntry>={};
  for(const entry of entries){const cat=categoryFor[entry.kind];if(cat){sourceItems.push({...entry,category:cat});sources[entry.id]=entry;}if(entry.kind==="Characters"&&entry.characterProfile?.relationships){const id=`relationships:${entry.id}`;sourceItems.push({id,title:`${entry.title} — relationships`,description:entry.characterProfile.relationships,category:"Relationships",cover:entry.cover,updatedAt:entry.updatedAt});sources[id]=entry;}}
  const items:BibleItem[]=[...sourceItems,...custom].map(e=>({...e,source:sources[e.id],status:canon[e.id]?.revision===e.updatedAt?canon[e.id].status:"Pending Review" as CanonStatus})).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
  const filtered=items.filter(e=>(tab==="Canon"||e.category===tab)&&(statusFilter==="All statuses"||e.status===statusFilter)&&`${e.title} ${e.description} ${e.category}`.toLowerCase().includes(query.toLowerCase()));
  const pending=items.find(e=>e.status==="Pending Review");
  useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
  function choose(next:string){setTab(next);setStatusFilter("All statuses");setShowAll(false);onQuery("");}
  function changeStatus(item:BibleItem,next:CanonStatus){onSave({workspace:{...project.workspace,canon:{...canon,[item.id]:{status:next,revision:item.updatedAt}}}},`${next}: ${item.title}`);}
  function edit(item?:BibleItem){if(item?.source){onEdit(item.source);return;}setSourceEpisodeId(item?.sourceEpisodeId||"");setEditing(item||null);setTitle(item?.title||"");setDescription(item?.description||"");setCategory(item?.category||(bibleCategories.includes(tab as BibleCategory)?tab as BibleCategory:"World"));setCover(item?.cover||project.cover||"fantasy");setStatus(item?.status||"Pending Review");setFeedback("");setOpen(true);}
  function save(){
    if(!title.trim()){setFeedback("Give this entry a name.");return;}
    const entry:BibleEntry={id:editing?.id||crypto.randomUUID(),title:title.trim(),description:description.trim(),category,cover,sourceEpisodeId:sourceEpisodeId||undefined,updatedAt:new Date().toISOString()};
    const kind=bibleEntryKinds[category];
    const nextCustom=custom.filter(e=>e.id!==entry.id);
    const nextEntries=kind?[...entries.filter(e=>e.id!==entry.id),{...entry,kind,status:"Not started" as const}]:entries;
    if(!kind)nextCustom.push(entry);
    if(onSave({workspace:{...project.workspace,entries:nextEntries,bibleEntries:nextCustom,canon:{...canon,[entry.id]:{status,revision:entry.updatedAt}}}},`${editing?"Updated":"Added"} story bible entry: ${entry.title}`)){setOpen(false);setFeedback("");setTab("Canon");setStatusFilter("All statuses");onQuery("");}
  }
  function exportBible(){const text=[`# ${project.title} — Story Bible`,project.workspace?.overview||project.idea,...bibleCategories.flatMap(cat=>{const group=items.filter(e=>e.category===cat);return group.length?[`\n## ${cat}`,...group.map(e=>`### ${e.title}\nStatus: ${e.status}\n\n${e.description}`)]:[];})].join("\n\n");const url=URL.createObjectURL(new Blob([text],{type:"text/markdown;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`${project.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-story-bible.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setFeedback("Story Bible exported.");}
  async function importNotes(upload?:File){if(!upload)return;if(!/\.(txt|md)$/i.test(upload.name)||upload.size>200000){setFeedback("Choose a .txt or .md file smaller than 200 KB.");return;}try{const content=await upload.text();if(content.length>50000){setFeedback("Please import notes with fewer than 50,000 characters.");return;}edit();setTitle(upload.name.replace(/\.(txt|md)$/i,""));setCategory("References");setDescription(content);setFeedback("Review your imported notes, then save the entry.");}catch{setFeedback("The file could not be read. Please try again.");}}
  function row(item:BibleItem){return <article className="bible-update" key={item.id}><button className="bible-entry-open" onClick={()=>edit(item)} aria-label={`Review ${item.title}`}><img src={art(item.cover)} alt=""/><span><strong>{item.title}</strong><span className="bible-badges"><span>{item.category}</span><span className={`bible-status status-${canonStatuses.indexOf(item.status)}`}>{item.status}</span></span><span className="bible-excerpt">{item.description||"Add the details that define this part of your world."}</span><time>{item.sourceEpisodeId ? `From ${entries.find(e=>e.kind==="Episodes"&&e.id===item.sourceEpisodeId)?.title||"an episode"} · ` : ""}{date(item.updatedAt)}</time></span></button><div className="bible-row-actions">{item.status==="Pending Review"&&<button className="project-secondary" aria-label={`Approve ${item.title}`} onClick={()=>changeStatus(item,"Confirmed Canon")}><Icon name="Check" size={16}/><span>Approve</span></button>}<details className="bible-entry-menu"><summary aria-label={`Manage ${item.title}`}>•••</summary><select aria-label={`Canon status for ${item.title}`} value={item.status} onChange={e=>changeStatus(item,e.target.value as CanonStatus)}>{canonStatuses.map(s=><option key={s}>{s}</option>)}</select></details></div></article>;}
  return <>
    <section className="bible-hero"><h1>Story Bible</h1><span className="bible-project-label">{project.title}</span><h2>Everything Aempy knows about your world.</h2><p>Keep your world consistent. Organize this project’s characters, places, and lore, and approve new canon as your episodes take shape.</p><blockquote>“A well-remembered<br/>world creates<br/>unforgettable stories.”<small>— Aempy</small></blockquote></section>
    <div className="bible-toolbar"><nav aria-label="Story Bible categories">{["Canon",...bibleCategories.filter(c=>c!=="Canon Rules")].map(name=><button key={name} aria-current={tab===name?"page":undefined} onClick={()=>choose(name)}>{name}</button>)}</nav><div><button className="project-secondary" onClick={exportBible}><Icon name="Export" size={16}/> Export</button><button className="project-primary" onClick={()=>edit()}>＋ Add Entry</button></div></div>
    <div className="bible-content"><div className="bible-main"><section className="bible-glance"><h2>World at a Glance</h2><p>The core of your story.</p><p className="bible-summary">{project.workspace?.overview||project.idea||"Every world starts with an idea. Add your world's summary."}</p><button className="project-secondary" onClick={onSummary}><Icon name="Edit" size={13}/> Edit Summary</button><span>Same world.<br/>New stories.</span></section><div className="bible-library"><nav className="bible-categories" aria-label="World library">{bibleCategories.map(cat=><button key={cat} aria-current={tab===cat?"page":undefined} onClick={()=>choose(cat)}><Icon name={categoryInfo[cat][0]} size={25}/><span><strong>{cat}</strong><small>{categoryInfo[cat][1]}</small></span><b>{items.filter(e=>e.category===cat).length}</b><Icon name="Arrow" size={15}/></button>)}</nav><section className="bible-panel bible-updates"><header><h2>{tab==="Canon"?"Recent Updates":tab}</h2><button onClick={()=>setShowAll(v=>!v)}>{showAll?"Show Recent":"View All"} →</button></header><div className={`bible-filter ${statusFilter==="All statuses"&&!showAll&&!query&&tab!=="Characters"?"collapsed":""}`}>{tab==="Characters"&&<button onClick={()=>onNavigate("Characters")}>Open character profiles →</button>}<label><span className="sr-only">Filter canon status</span><select aria-label="Filter canon status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}>{["All statuses",...canonStatuses].map(s=><option key={s}>{s}</option>)}</select></label>{(query||statusFilter!=="All statuses")&&<button onClick={()=>{onQuery("");setStatusFilter("All statuses");}}>Clear filters</button>}</div>{filtered.length?(showAll||tab!=="Canon"||query||statusFilter!=="All statuses"?filtered:filtered.slice(0,5)).map(row):<div className="bible-empty"><Icon name="Lore" size={34}/><h3>{items.length?"No matching entries":"Your world starts here"}</h3><p>{items.length?"Try another category or search, or add something new.":"Save the places, people, and rules that make your story unforgettable."}</p><button className="project-primary" onClick={()=>edit()}>＋ Add an Entry</button></div>}</section></div></div>
    <aside className="bible-right"><section className="bible-panel"><header><h2><Icon name="Factions" size={20}/> Canon Status</h2><button onClick={()=>{choose("Canon");setStatusFilter("Pending Review");}}>Manage</button></header><div className="bible-counts">{(["Confirmed Canon","Pending Review","Needs Clarification","Contradictions"] as CanonStatus[]).map(s=><button key={s} onClick={()=>{choose("Canon");setStatusFilter(s);}}><i className={`status-dot status-${canonStatuses.indexOf(s)}`}/><span>{s}</span><b>{items.filter(e=>e.status===s).length}</b></button>)}</div></section>
    <section className="bible-panel bible-pending"><header><h2>Awaiting Review</h2><button onClick={()=>{choose("Canon");setStatusFilter("Pending Review");}}>View All →</button></header>{pending?<div className="bible-pending-body"><img src={art(pending.cover)} alt=""/><div><h3>{pending.title}</h3><small>{pending.category}</small><p>{pending.description||"Review this entry and decide what belongs in your world's canon."}</p><div><button className="project-primary" onClick={()=>changeStatus(pending,"Confirmed Canon")}>✓ Approve</button><button className="project-secondary" onClick={()=>edit(pending)}>Review</button></div></div></div>:<div className="bible-empty small"><Icon name="Check"/><p>{items.length?"You're all caught up. No entries are waiting for review.":"New entries will appear here for your approval."}</p></div>}</section>
    <section className="bible-panel bible-quick"><header><h2>Quick Actions</h2></header>{[["Search","Search my world"],["Create","Add a custom entry"],["Export","Import notes / document"],["Image","Add a visual reference"]].map(([icon,label],i)=><button key={label} onClick={()=>{if(i===0){choose("Canon");document.querySelector<HTMLInputElement>('[aria-label="Search this project"]')?.focus();}if(i===1)edit();if(i===2)file.current?.click();if(i===3){edit();setCategory("Visual Style");}}}><Icon name={icon} size={20}/><span>{label}</span><Icon name="Arrow" size={16}/></button>)}<input type="file" hidden ref={file} accept=".txt,.md,text/plain,text/markdown" onChange={e=>{void importNotes(e.target.files?.[0]);e.target.value="";}}/></section><p className="bible-footnote">You decide what becomes canon. Editing a source entry returns it to review. Saved in this browser.</p></aside></div><p className="bible-notice" role="status">{feedback||notice}</p>
    <dialog ref={dialog} className="studio-dialog project-editor" onCancel={()=>setOpen(false)}><button className="project-dialog-close" aria-label="Close Story Bible editor" onClick={()=>setOpen(false)}>×</button><form onSubmit={e=>{e.preventDefault();save();}}><p className="studio-eyebrow">YOUR WORLD, YOUR RULES</p><h2>{editing?"Edit Entry":"New Story Bible Entry"}</h2><label>Entry name<input aria-label="Entry name" value={title} maxLength={100} required onChange={e=>setTitle(e.target.value)}/></label><label>Category<select aria-label="Entry category" value={category} onChange={e=>setCategory(e.target.value as BibleCategory)}>{bibleCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Source episode<select aria-label="Source episode" value={sourceEpisodeId} onChange={e=>{setSourceEpisodeId(e.target.value);setStatus("Pending Review");}}><option value="">World-building note</option>{entries.filter(e=>e.kind==="Episodes").map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Details<textarea aria-label="Entry details" value={description} maxLength={50000} onChange={e=>setDescription(e.target.value)}/></label><label>Canon status<select aria-label="Entry canon status" value={status} onChange={e=>setStatus(e.target.value as CanonStatus)}>{canonStatuses.map(s=><option key={s}>{s}</option>)}</select></label><fieldset><legend>Reference artwork</legend><div className="project-cover-choices">{projectArt.map(name=><button type="button" key={name} aria-label={`${name} reference`} aria-pressed={cover===name} className={cover===name?"selected":""} onClick={()=>setCover(name)}><img src={art(name)} alt=""/></button>)}</div></fieldset><button type="submit" className="project-primary">Save Entry <Icon name="Arrow" size={16}/></button><p role="status">{feedback||notice}</p></form></dialog>
  </>;
}
